config/routes.rb
Foreman::Application.routes.draw do
  namespace :foreman_tasks do
    resources :recurring_logics, :only => [:index, :show] do
      member do
        post :cancel
        put :enable
        put :disable
      end
      collection do
        get 'auto_complete_search'
        post :clear_cancelled
      end
    end

    resources :tasks, :only => [:show] do
      collection do
        get 'auto_complete_search'
        get '/summary/:recent_timeframe', action: 'summary'
        get '/summary/:id/sub_tasks/:recent_timeframe', action: 'summary_sub_tasks'
      end
      member do
        post :abort
        post :cancel
        post :resume
        post :unlock
        post :force_unlock
        post :cancel_step
      end
    end
    resources :tasks, :only => [:show], constraints: ->(req) { req.format == :csv } do
      member do
        get :sub_tasks
      end
    end
    resources :tasks, :only => [:index], constraints: ->(req) { req.format == :csv }

    match '/tasks' => 'react#index', :via => [:get]
    match '/tasks/:id/sub_tasks' => 'react#index', :via => [:get]
    match '/ex_tasks/:id' => 'react#index', :via => [:get]

    namespace :api do
      resources :recurring_logics, :only => [:index, :show, :update] do
        member do
          post :cancel
        end
        collection do
          post :bulk_destroy
        end
      end

      resources :tasks, :only => [:show, :index] do
        member do
          get :details
        end
        collection do
          post :bulk_search
          post :bulk_resume
          post :bulk_cancel
          post :bulk_stop
          get :summary
          get '/:parent_task_id/sub_tasks', action: 'index'
          get '/summary/:id/sub_tasks/', action: 'summary_sub_tasks'
          post :callback
        end
      end
    end

    if ForemanTasks.dynflow.required?
      require 'dynflow/web'
      mount ForemanTasks.dynflow.web_console => '/dynflow'
      if defined? ::Sidekiq
        require 'sidekiq/web'
        redis_url = ENV['DYNFLOW_REDIS_URL'] || SETTINGS.dig(:dynflow, :redis_url)
        Sidekiq.redis = { url: redis_url }
        mount Sidekiq::Web => '/sidekiq', :constraints => ForemanTasks::Dynflow::SidekiqConsoleConstraint.new
      end
    end
  end
end

app/models/foreman_tasks/task_group.rb
module ForemanTasks
  class TaskGroup < ApplicationRecord
    has_many :task_group_members, :dependent => :destroy
    has_many :tasks, :through => :task_group_members, :dependent => :nullify

    def resource_name
      raise NotImplementedError
    end

    def resource
      raise NotImplementedError
    end
  end
end

app/models/foreman_tasks/task_groups/recurring_logic_task_group.rb
module ForemanTasks
  module TaskGroups
    class RecurringLogicTaskGroup < ::ForemanTasks::TaskGroup
      has_one :recurring_logic, :foreign_key => :task_group_id, :dependent => :nullify

      alias resource recurring_logic

      def resource_name
        N_('Recurring logic')
      end
    end
  end
end

app/views/foreman_tasks/task_groups/recurring_logic_task_groups/_recurring_logic_task_group.html.erb
<% recurring_logic = task_group.recurring_logic -%>
<table class='<%= table_css_classes('table-condensed') %>'>
  <tr>
    <th><%= _('ID') %></th>
    <td><%= link_to(recurring_logic.id, recurring_logic) %></td>
  </tr>
  <tr>
    <th><%= _("Cron line") %></th>
    <td><%= recurring_logic.cron_line %></td>
  </tr>
  <tr>
    <th><%= _("Action") %></th>
    <td><%= format_task_input(recurring_logic.tasks.last) %></td>
  </tr>
  <tr>
    <th><%= _("Last occurrence") %></th>
    <td><%= recurring_logic.tasks.order(:started_at).where('started_at IS NOT NULL').last.try(:started_at) || '-' %></td>
  </tr>
  <tr>
    <th><%= _("Next occurrence") %></th>
    <td><%= recurring_logic_next_occurrence recurring_logic %></td>
  </tr>
  <tr>
    <th><%= _("Current iteration") %></th>
    <td><%= recurring_logic.iteration %></td>
  </tr>
  <tr>
    <th><%= _("Iteration limit") %></th>
    <td><%= format_recurring_logic_limit recurring_logic.max_iteration %></td>
  </tr>
  <tr>
    <th><%= _("Repeat until") %></th>
    <td><%= format_recurring_logic_limit recurring_logic.end_time.try(:in_time_zone) %></td>
  </tr>
  <tr>
    <th><%= _("State") %></th>
    <td><%= recurring_logic_state(recurring_logic) %></td>
  </tr>
  <tr>
    <th><%= _("Purpose") %></th>
    <td><%= recurring_logic.purpose %></td>
  </tr>
  <tr>
    <th><%= _("Task count") %></th>
    <td><%= link_to(task_group.tasks.count, foreman_tasks_tasks_url(:search => "task_group.id = #{task_group.id}")) %></td>
  </tr>
</table>